name: Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build Frontend
      run: npm run build
      env:
        VITE_API_URL: http://localhost:3000
        VITE_JSON_SERVER_URL: http://localhost:3001

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Frontend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.frontend
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        target: development
        build-args: |
          VITE_API_URL=http://localhost:3000
          VITE_JSON_SERVER_URL=http://localhost:3001

  json-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      working-directory: ./json-server
      run: npm i

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build JSON Server Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.jsonserver
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max

  llm-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./llm-server/package-lock.json

    - name: Install Dependencies
      working-directory: ./llm-server
      run: npm ci

    - name: Build LLM Server
      working-directory: ./llm-server
      run: npm run build
      env:
        NODE_ENV: development
        PORT: 3000
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build LLM Server Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./llm-server/Dockerfile
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          NODE_ENV=development
